"""Quality gate and production audit prompts.

The quality gate is DETERMINISTIC — it runs actual tools and extracts numeric metrics.
The production audit is AI-based but informed by gate results.
"""

from __future__ import annotations


def quality_gate(task_id: str, task_title: str, thresholds: dict) -> str:
    """Prompt for deterministic quality gate — extracts numeric metrics."""
    threshold_text = ", ".join(f"{k}={v}" for k, v in thresholds.items())
    return (
        f"Quality gate for task {task_id}: \"{task_title}\"\n\n"
        "Run these checks and extract EXACT numbers:\n"
        "1. BUILD: run build command → build: true/false\n"
        "2. TESTS: run test suite with coverage → tests: true/false, test_coverage: number\n"
        "   (Python: pytest --cov | grep TOTAL, Node: jest --coverage | grep All files)\n"
        "3. LINT: run linter → lint: true/false (zero errors)\n"
        "4. FILE SIZE: wc -l on changed source files → max_file_lines: largest count\n"
        "5. FUNCTION SIZE: count lines of largest function → max_function_lines: number\n"
        "6. SECURITY: run scanner + grep for hardcoded secrets → security_critical: count\n"
        "   (Python: bandit -r . -f json, Node: npm audit --json)\n"
        "   (grep -rn 'password.*=.*[\"\\']' for hardcoded secrets)\n"
        "7. ACCESSIBILITY (frontend only): → a11y_critical: count\n"
        "   - If project has frontend (React/Next.js/Vue): run axe-core or eslint-plugin-jsx-a11y\n"
        "   - Check: missing alt text, missing aria-labels, non-semantic elements, color contrast\n"
        "   - If no frontend: a11y_critical: 0\n"
        "8. FRONTEND DESIGN (frontend only — informational, not gated):\n"
        "   - grep for hardcoded color values (e.g., #fff, rgb()) outside design token files\n"
        "   - grep for hardcoded px values in layout (should use spacing tokens)\n"
        "   - Report findings as warnings (not gate failures)\n\n"
        "9. CODE QUALITY (server-side verified — informational):\n"
        "   The server automatically detects: magic numbers, duplicate code blocks,\n"
        "   unused imports, N+1 query patterns, and hardcoded repeated strings.\n"
        "   These are reported as warnings and passed to the production audit.\n"
        "   Fix proactively — the audit agent WILL see these violations.\n\n"
        "IMPORTANT: Report EXACT numbers for ALL metrics. If a metric cannot be measured\n"
        "(e.g., no frontend = no a11y check), report the metric as 0 or true as appropriate.\n"
        "Do NOT omit any metric — omitted metrics cause automatic gate failure.\n\n"
        "ACCOUNTABILITY: Your measurements will be cross-verified server-side.\n"
        "If your reported scores do not match actual measurements, the gate fails\n"
        "and you will be asked to re-measure. Report only what you can verify.\n\n"
        f"Thresholds (ALL must be met): {threshold_text}\n\n"
        "Call harmony_pipeline_next with:\n"
        f'{{"step":"quality_gate","task_id":"{task_id}","task_title":"{task_title}","scores":{{\n'
        '  "build":true/false, "tests":true/false, "test_coverage":<N>,\n'
        '  "lint":true/false, "max_file_lines":<N>, "max_function_lines":<N>,\n'
        '  "security_critical":<N>, "a11y_critical":<N>\n'
        "}}"
    )


def production_audit(task_id: str, task_title: str) -> str:
    """Prompt for project-context-aware production audit."""
    return (
        f'Production audit for task {task_id}: "{task_title}"\n\n'
        "**CRITICAL: You MUST use the Agent tool to spawn a NEW agent for this audit.**\n"
        "Do NOT review the code yourself — you built it, so you are biased.\n"
        "The Agent tool creates a fresh context with no memory of the build.\n\n"
        "Call Agent with this prompt (copy exactly):\n\n"
        '  "You are a senior engineer performing a production audit.\n'
        "  You have NO context about how this code was built.\n"
        "  You see ONLY the code output — not the process, reasoning, or intentions.\n"
        "  Treat every file as if written by an untrusted stranger.\n\n"
        f"  Task: {task_title}\n\n"
        "  STEP 1 — UNDERSTAND THE PROJECT\n"
        "  Read these files to understand the project's domain and requirements:\n"
        "  - docs/prd.md (the spec — what this project should do)\n"
        "  - docs/refs/*.md (domain reference docs — expert knowledge per area)\n"
        "  - CLAUDE.md (project rules and conventions)\n"
        "  - .harmony/state.json → quality_scores._code_quality_details (server-detected issues)\n\n"
        "  STEP 2 — FIND CHANGED FILES\n"
        "  git merge-base HEAD main (or develop/master), then:\n"
        "  git diff --name-only <merge-base>...HEAD\n"
        "  Do NOT use HEAD~1 — tasks may span multiple commits.\n\n"
        "  STEP 3 — AUDIT BY CATEGORY\n"
        "  Review the changed files against each applicable category below.\n"
        "  Skip categories that don't apply (e.g., skip DB if no database in this project).\n"
        "  For each category, give a verdict: PASS / NEEDS_FIX with specific issues.\n\n"
        "  **A. Bugs & Logic**\n"
        "  - Logic errors, off-by-one, inverted booleans, missing returns\n"
        "  - Null/undefined access, race conditions, type mismatches\n"
        "  - Boundary conditions: empty arrays, zero/negative, max values\n\n"
        "  **B. Code Quality & Constants**\n"
        "  - DRY: duplicated logic → shared functions/utilities\n"
        "  - Magic numbers/strings → named constants\n"
        "  - Naming: clear, consistent, meaningful\n"
        "  - Dead code, commented-out code, unused imports\n"
        "  - MANDATORY: check .harmony/state.json quality_scores._code_quality_details\n"
        "    For each server-detected issue (magic_numbers, duplicate_code, unused_imports,\n"
        "    nplus1_queries, hardcoded_strings), you MUST either flag it as MUST-FIX\n"
        "    or explain why it is a false positive. You may NOT ignore them.\n\n"
        "  **C. Architecture & Structure** (based on PRD)\n"
        "  - Does the code structure match the PRD's architecture?\n"
        "  - Separation of concerns: are layers properly isolated?\n"
        "  - Common components: repeated patterns → shared abstractions\n"
        "  - Module boundaries: are dependencies going in the right direction?\n\n"
        "  **D. Business Logic** (based on PRD + refs)\n"
        "  - Does the implementation match the PRD's feature spec?\n"
        "  - State machines: are all transitions valid? Missing states?\n"
        "  - Domain rules: are business constraints enforced in code?\n"
        "  - Edge cases specific to this domain\n\n"
        "  **E. Database & Schema** (if applicable)\n"
        "  - Schema matches PRD data model?\n"
        "  - Proper indexes for query patterns\n"
        "  - Relationships and constraints (FK, unique, not null)\n"
        "  - N+1 queries, missing pagination, unbounded fetches\n"
        "  - Migration safety\n\n"
        "  **F. API & Integration**\n"
        "  - API contracts match PRD spec\n"
        "  - Input validation on all endpoints\n"
        "  - Error responses: structured, consistent, informative\n"
        "  - Security: auth checks, no hardcoded secrets, CORS\n\n"
        "  **G. Frontend & UX** (if applicable)\n"
        "  - Responsive: works at mobile/tablet/desktop\n"
        "  - States: loading, empty, error — all handled\n"
        "  - Design system: tokens used, no hardcoded colors/spacing\n"
        "  - Accessibility: semantic HTML, aria, keyboard navigation\n"
        "  - User flow: does the UX make sense for the target user in the PRD?\n\n"
        "  **H. Test Quality**\n"
        "  - Meaningful assertions (not trivial expect(true))\n"
        "  - Edge cases and error paths tested\n"
        "  - Coverage of critical business logic\n\n"
        "  **I. Performance** (if applicable)\n"
        "  - N+1 queries, unnecessary re-renders, missing memoization\n"
        "  - Unbounded data fetches, expensive operations in hot paths\n\n"
        "  STEP 4 — REPORT\n"
        "  For each applicable category (A-I):\n"
        "    Category: PASS or NEEDS_FIX\n"
        "    Issues (if any): file:line, severity (MUST-FIX/SHOULD-FIX), what, how to fix\n\n"
        "  Overall verdict: PASS only if ALL applicable categories pass.\n"
        "  Default to NEEDS_FIX. Passing bad code is worse than flagging a false positive.\n"
        '  Be RUTHLESS. You are accountable."\n\n'
        "After the Agent returns, call harmony_pipeline_next with:\n"
        f'{{"step":"audit","task_id":"{task_id}","auditor_id":"<agent-id-from-Agent-tool>",'
        '"verdict":"PASS"/"NEEDS_FIX","issues":[...]}}\n\n'
        "CRITICAL: auditor_id is REQUIRED. The pipeline will REJECT audit results without it.\n"
        "Use the agent ID returned by the Agent tool."
    )
